#!/usr/bin/env python3
"""Build a deterministic runtime env file from a potentially duplicated .env.

Why:
- `.env` often accumulates repeated keys while tuning.
- dotenv resolves by "last assignment wins", but that is easy to lose track of.
- This script flattens to one key=value per key so runs are reproducible.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

BASE = Path("/Users/nickdavis/MOON DEV BOT/moon-dev-ai-agents")
ENV_RE = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$")


def parse_env(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not path.exists():
        return out
    for raw in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        m = ENV_RE.match(raw)
        if not m:
            continue
        key = m.group(1).strip()
        val = m.group(2)
        # Move to end so order reflects final precedence.
        if key in out:
            out.pop(key, None)
        out[key] = val
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", default=str(BASE / ".env"), help="input .env path")
    ap.add_argument("--out", dest="out", default=str(BASE / "data" / "meme_runtime.env"), help="output env path")
    args = ap.parse_args()

    inp = Path(args.inp)
    out = Path(args.out)
    kv = parse_env(inp)
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by scripts/build_runtime_env.py",
        "# Deterministic flattened env (last assignment wins).",
        "",
    ]
    lines.extend(f"{k}={v}" for k, v in kv.items())
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out} keys={len(kv)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
