#!/usr/bin/env python3
"""Keep the meme pipeline processes alive and log restarts."""
from __future__ import annotations

import os
import json
import subprocess
import time
import fcntl
from dataclasses import dataclass
from pathlib import Path

from dotenv import load_dotenv

BASE = Path("/Users/nickdavis/MOON DEV BOT/moon-dev-ai-agents")
LOGS = BASE / "logs"
LOGS.mkdir(parents=True, exist_ok=True)
NEXT_TUNING = BASE / "data" / "next_tuning.json"
AUTO_TUNING_LOG = LOGS / "meme_auto_tuning.log"
REAP_LOG = LOGS / "reap_stale_positions.log"
LOCK_FILE = LOGS / "meme_pipeline_supervisor.lock"

PYTHON = "/opt/homebrew/bin/python3"
_LOCK_FH = None

@dataclass
class ProcSpec:
    name: str
    cmd: list[str]
    log_path: Path


def spawn(spec: ProcSpec, env: dict[str, str]) -> subprocess.Popen:
    # Keep a dedicated log file per child process. Close the parent handle
    # immediately after spawn so repeated restarts don't leak descriptors.
    with open(spec.log_path, "a", encoding="utf-8") as log:
        # start_new_session detaches process group so it survives shell exits
        proc = subprocess.Popen(
            spec.cmd,
            stdout=log,
            stderr=subprocess.STDOUT,
            start_new_session=True,
            cwd=str(BASE),
            env=env,
        )
    return proc


def _acquire_singleton_lock() -> bool:
    """Ensure only one supervisor instance runs at a time."""
    global _LOCK_FH
    try:
        LOCK_FILE.parent.mkdir(parents=True, exist_ok=True)
        fh = open(LOCK_FILE, "a+", encoding="utf-8")
        fcntl.flock(fh.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
        fh.seek(0)
        fh.truncate()
        fh.write(f"{os.getpid()}\n")
        fh.flush()
        _LOCK_FH = fh  # keep file handle alive for lock lifetime
        return True
    except OSError:
        return False
    except Exception:
        return False

def build_env() -> dict[str, str]:
    """Reload .env and return the environment dict for child processes.

    This makes tuning iteration smoother: updating `.env` and restarting a single
    process is enough; we do not need to restart the whole supervisor.
    """
    # 1) Load primary project env.
    primary_env = BASE / ".env"
    load_dotenv(dotenv_path=str(primary_env), override=True)
    # 2) Optional deterministic runtime env (flattened from `.env`).
    runtime_env_raw = str(os.getenv("MEME_ENV_FILE", "") or "").strip()
    if runtime_env_raw:
        runtime_env = Path(runtime_env_raw)
        if not runtime_env.is_absolute():
            runtime_env = BASE / runtime_env
        if runtime_env.exists():
            load_dotenv(dotenv_path=str(runtime_env), override=True)
    env = os.environ.copy()
    # Default to whatever the user has in .env; only set a fallback if none is present.
    env.setdefault("RPC_URL", env.get("RPC_ENDPOINT", "") or "")
    # If an RPC pool was generated by scripts/key_health_check.py, allow consumers to rotate automatically.
    # Prefer config/rpc_pool.json (gitignored) to avoid accidentally committing provider URLs.
    env.setdefault("RPC_POOL_FILE", str(BASE / "config" / "rpc_pool.json"))
    return env

def build_specs(env: dict[str, str]) -> list[ProcSpec]:
    """Build the desired process list from env.

    Important: this is evaluated repeatedly in the supervisor loop so changing
    `.env` can add/remove pipeline components without restarting the supervisor.
    """
    # Prefer WS discovery when a WSS endpoint is configured.
    # Note: the WS scaffold supports HELIUS_WS_URLS (CSV) as well as HELIUS_WS_URL.
    use_ws = bool(env.get("HELIUS_WS_URLS") or env.get("HELIUS_WS_URL") or env.get("HELIUS_WS"))
    enable_pump_ws = env.get("MEME_ENABLE_PUMP_WS", "0").strip().lower() in ("1", "true", "yes")
    enable_raydium_ws = env.get("MEME_ENABLE_RAYDIUM_WS", "1").strip().lower() in ("1", "true", "yes")
    enable_dex_mover = env.get("MEME_ENABLE_DEX_MOVER", "1").strip().lower() in ("1", "true", "yes")
    enable_wallet_outlier = env.get("MEME_ENABLE_WALLET_OUTLIER", "0").strip().lower() in ("1", "true", "yes")
    enable_leaderboard_wallet_discovery = env.get("MEME_LEADERBOARD_WALLET_DISCOVERY", "0").strip().lower() in (
        "1",
        "true",
        "yes",
    )
    enable_main_bot = env.get("MEME_SUPERVISOR_ENABLE_BOT", "1").strip().lower() in ("1", "true", "yes")
    enable_paper_v1 = env.get("MEME_PAPER_OVERLAY_V1_ENABLED", "1").strip().lower() in ("1", "true", "yes")
    enable_paper_v2 = env.get("MEME_PAPER_OVERLAY_V2_ENABLED", "1").strip().lower() in ("1", "true", "yes")
    enable_paper_active = env.get("MEME_PAPER_OVERLAY_ACTIVE_ENABLED", "1").strip().lower() in ("1", "true", "yes")
    # These names can round-trip in minutes, so a 5-minute paper loop is too slow
    # to teach us anything useful about risk control.
    paper_interval = str(int(float(env.get("MEME_PAPER_OVERLAY_INTERVAL_SEC", "60") or 60)))
    paper_max_hold = str(float(env.get("MEME_PAPER_OVERLAY_MAX_HOLD_HOURS", "12") or 12))
    paper_v1_no_refresh = env.get("MEME_PAPER_V1_NO_REFRESH", "1").strip().lower() in ("1", "true", "yes")
    paper_v2_no_refresh = env.get("MEME_PAPER_V2_NO_REFRESH", "0").strip().lower() in ("1", "true", "yes")
    paper_active_no_refresh = env.get("MEME_PAPER_ACTIVE_NO_REFRESH", "0").strip().lower() in ("1", "true", "yes")

    specs: list[ProcSpec] = []

    if use_ws:
        if enable_raydium_ws:
            specs.append(
                ProcSpec(
                    name="raydium_pool_ws_listener",
                    cmd=[PYTHON, "-u", str(BASE / "scripts" / "raydium_pool_ws_listener.py")],
                    log_path=LOGS / "raydium_pool_ws_listener.log",
                )
            )
        if enable_pump_ws:
            specs.append(
                ProcSpec(
                    name="pump_ws_signal_listener",
                    cmd=[PYTHON, "-u", str(BASE / "scripts" / "pump_ws_signal_listener.py")],
                    log_path=LOGS / "pump_ws_signal_listener.log",
                )
            )
    else:
        # Fallback to HTTP polling when WS is unavailable.
        specs.extend(
            [
                ProcSpec(
                    name="solana_log_poller",
                    cmd=[
                        PYTHON,
                        "-u",
                        str(BASE / "scripts/solana_log_poller.py"),
                        "--programs-file",
                        str(BASE / "config/helius_programs.json"),
                        "--poll",
                        "12",
                        "--limit",
                        "10",
                        "--mints-out",
                        str(BASE / "data/meme_launch_mints.jsonl"),
                    ],
                    log_path=LOGS / "solana_log_poller.log",
                ),
                ProcSpec(
                    name="meme_onchain_signal_tracker",
                    cmd=[
                        PYTHON,
                        "-u",
                        str(BASE / "scripts/meme_onchain_signal_tracker.py"),
                        "--input",
                        str(BASE / "data/meme_launch_mints.jsonl"),
                        "--out",
                        str(BASE / "data/meme_launch_signals.jsonl"),
                        "--poll",
                        "3",
                    ],
                    log_path=LOGS / "meme_onchain_signal_tracker.log",
                ),
            ]
        )

    specs.extend(
        [
            ProcSpec(
                name="dex_mover_signal_listener",
                cmd=[PYTHON, "-u", str(BASE / "scripts" / "dex_mover_signal_listener.py")],
                log_path=LOGS / "dex_mover_signal_listener.log",
            ),
            ProcSpec(
                name="leaderboard_wallet_discovery",
                cmd=[PYTHON, "-u", str(BASE / "scripts" / "leaderboard_wallet_discovery.py")],
                log_path=LOGS / "leaderboard_wallet_discovery.log",
            ),
            ProcSpec(
                name="wallet_outlier_signal_listener",
                cmd=[PYTHON, "-u", str(BASE / "scripts" / "wallet_outlier_signal_listener.py")],
                log_path=LOGS / "wallet_outlier_signal_listener.log",
            ),
            ProcSpec(
                name="signal_outcome_recorder",
                cmd=[PYTHON, "-u", str(BASE / "scripts/signal_outcome_recorder.py")],
                log_path=LOGS / "signal_outcome_recorder.log",
            ),
            ProcSpec(
                name="meme_pipeline_health",
                cmd=[PYTHON, "-u", str(BASE / "scripts/meme_pipeline_health.py")],
                log_path=LOGS / "meme_pipeline_health.log",
            ),
            ProcSpec(
                name="meme_edge_reporter",
                cmd=[PYTHON, "-u", str(BASE / "scripts/meme_edge_reporter.py")],
                log_path=LOGS / "meme_edge_reporter.log",
            ),
            ProcSpec(
                name="meme_edge_decider",
                cmd=[PYTHON, "-u", str(BASE / "scripts/meme_edge_decider.py")],
                log_path=LOGS / "meme_edge_decider.log",
            ),
        ]
    )
    if not enable_dex_mover:
        specs = [s for s in specs if s.name != "dex_mover_signal_listener"]
    if not enable_leaderboard_wallet_discovery:
        specs = [s for s in specs if s.name != "leaderboard_wallet_discovery"]
    if not enable_wallet_outlier:
        specs = [s for s in specs if s.name != "wallet_outlier_signal_listener"]
    if enable_main_bot:
        specs.append(
            ProcSpec(
                name="meme_bot",
                cmd=[PYTHON, "-u", str(BASE / "src/meme_bot.py")],
                log_path=LOGS / "meme_bot_early_edge_auto.log",
            )
        )

    # Optional: hourly Discord summary (posts a compact perf summary to your webhook)
    if env.get("MEME_HOURLY_SUMMARY_ENABLED", "0").strip().lower() in ("1", "true", "yes"):
        specs.append(
            ProcSpec(
                name="meme_hourly_discord_summary",
                cmd=[PYTHON, "-u", str(BASE / "scripts/meme_hourly_discord_summary.py")],
                log_path=LOGS / "meme_hourly_discord_summary.log",
            )
        )

    # Optional: hourly loss-cause ranking report (exit reasons + feature buckets).
    if env.get("MEME_HOURLY_LOSS_REPORT_ENABLED", "0").strip().lower() in ("1", "true", "yes"):
        specs.append(
            ProcSpec(
                name="meme_hourly_loss_report",
                cmd=[PYTHON, "-u", str(BASE / "scripts/meme_hourly_loss_report.py")],
                log_path=LOGS / "meme_hourly_loss_report.log",
            )
        )

    # Optional: continuously print attribution so we can tune one knob at a time.
    if env.get("MEME_AUTO_ATTRIBUTION", "0").strip().lower() in ("1", "true", "yes"):
        specs.append(
            ProcSpec(
                name="meme_auto_attribution",
                cmd=[PYTHON, "-u", str(BASE / "scripts" / "meme_auto_attribution.py")],
                log_path=LOGS / "meme_auto_attribution.log",
            )
        )

    # Optional: continuously rebuild winner profile from latest trade outcomes.
    if env.get("MEME_WINNER_PROFILE_AUTO_BUILD", "0").strip().lower() in ("1", "true", "yes"):
        specs.append(
            ProcSpec(
                name="meme_winner_profile_watcher",
                cmd=[PYTHON, "-u", str(BASE / "scripts" / "meme_winner_profile_watcher.py")],
                log_path=LOGS / "meme_winner_profile_watcher.log",
            )
        )

    # Optional: continuously rebuild winner-zone allowlist from signal outcomes.
    if env.get("MEME_WINNER_ZONE_AUTO_BUILD", "0").strip().lower() in ("1", "true", "yes"):
        specs.append(
            ProcSpec(
                name="meme_winner_zone_watcher",
                cmd=[PYTHON, "-u", str(BASE / "scripts" / "meme_winner_zone_watcher.py")],
                log_path=LOGS / "meme_winner_zone_watcher.log",
            )
        )

    # Optional: continuous metadata quality report generation.
    if env.get("MEME_METADATA_QUALITY_AUTO_REPORT", "0").strip().lower() in ("1", "true", "yes"):
        specs.append(
            ProcSpec(
                name="meme_metadata_quality_watcher",
                cmd=[PYTHON, "-u", str(BASE / "scripts" / "meme_metadata_quality_watcher.py")],
                log_path=LOGS / "meme_metadata_quality_watcher.log",
            )
        )

    # Optional: track opportunity cost from reject logs (what likely-good mints we are blocking).
    if env.get("MEME_OPPORTUNITY_COST_AUTO_REPORT", "0").strip().lower() in ("1", "true", "yes"):
        specs.append(
            ProcSpec(
                name="meme_opportunity_cost_watcher",
                cmd=[PYTHON, "-u", str(BASE / "scripts" / "meme_opportunity_cost_watcher.py")],
                log_path=LOGS / "meme_opportunity_cost_watcher.log",
            )
        )

    # Optional: periodically decide if scout lane should be kept/tightened/disabled.
    if env.get("MEME_SCOUT_DECIDER_AUTO", "0").strip().lower() in ("1", "true", "yes"):
        specs.append(
            ProcSpec(
                name="meme_scout_decider_watcher",
                cmd=[PYTHON, "-u", str(BASE / "scripts" / "meme_scout_decider_watcher.py")],
                log_path=LOGS / "meme_scout_decider_watcher.log",
            )
        )

    # Optional: walk-forward tuner for prequote winner gates (offline from local outcomes).
    if env.get("MEME_PREQUOTE_WF_AUTO", "0").strip().lower() in ("1", "true", "yes"):
        specs.append(
            ProcSpec(
                name="meme_prequote_walkforward_watcher",
                cmd=[PYTHON, "-u", str(BASE / "scripts" / "meme_prequote_walkforward_watcher.py")],
                log_path=LOGS / "meme_prequote_walkforward_watcher.log",
            )
        )

    # Optional: run-scoped report for mints that pass prequote but fail downstream.
    if env.get("MEME_WINNER_MISS_AUTO_REPORT", "0").strip().lower() in ("1", "true", "yes"):
        specs.append(
            ProcSpec(
                name="meme_winner_miss_watcher",
                cmd=[PYTHON, "-u", str(BASE / "scripts" / "meme_winner_miss_watcher.py")],
                log_path=LOGS / "meme_winner_miss_watcher.log",
            )
        )

    # Optional: auto-generate run decision bundle once sample/readiness thresholds are met.
    if env.get("MEME_SAMPLE_READY_WATCHER", "0").strip().lower() in ("1", "true", "yes"):
        specs.append(
            ProcSpec(
                name="meme_sample_ready_watcher",
                cmd=[PYTHON, "-u", str(BASE / "scripts" / "meme_sample_ready_watcher.py")],
                log_path=LOGS / "meme_sample_ready_watcher.log",
            )
        )

    # Optional: periodic baseline-vs-zone A/B report snapshots.
    if env.get("MEME_AB_ZONE_REPORT_WATCHER", "0").strip().lower() in ("1", "true", "yes"):
        specs.append(
            ProcSpec(
                name="meme_ab_zone_watcher",
                cmd=[PYTHON, "-u", str(BASE / "scripts" / "meme_ab_zone_watcher.py")],
                log_path=LOGS / "meme_ab_zone_watcher.log",
            )
        )

    # Optional: periodic tri-lane report snapshots (base vs match-only vs bypass-only).
    if env.get("MEME_AB_ZONE_TRI_WATCHER", "0").strip().lower() in ("1", "true", "yes"):
        specs.append(
            ProcSpec(
                name="meme_ab_zone_tri_watcher",
                cmd=[PYTHON, "-u", str(BASE / "scripts" / "meme_ab_zone_tri_watcher.py")],
                log_path=LOGS / "meme_ab_zone_tri_watcher.log",
            )
        )

    # Keep the paper trader live so the project keeps producing decision outcomes.
    if enable_paper_v1:
        cmd = [
            PYTHON,
            "-u",
            str(BASE / "scripts" / "meme_decision_paper_overlay.py"),
            "--loop",
            "--interval-sec",
            paper_interval,
            "--max-hold-hours",
            paper_max_hold,
        ]
        if paper_v1_no_refresh:
            cmd.append("--no-refresh")
        specs.append(
            ProcSpec(
                name="meme_decision_paper_overlay",
                cmd=cmd,
                log_path=LOGS / "meme_decision_paper_overlay.loop.log",
            )
        )

    if enable_paper_v2:
        cmd = [
            PYTHON,
            "-u",
            str(BASE / "scripts" / "meme_decision_paper_overlay_v2.py"),
            "--loop",
            "--interval-sec",
            paper_interval,
            "--max-hold-hours",
            paper_max_hold,
        ]
        if paper_v2_no_refresh:
            cmd.append("--no-refresh")
        specs.append(
            ProcSpec(
                name="meme_decision_paper_overlay_v2",
                cmd=cmd,
                log_path=LOGS / "meme_decision_paper_overlay_v2.loop.log",
            )
        )

    if enable_paper_active:
        cmd = [
            PYTHON,
            "-u",
            str(BASE / "scripts" / "meme_decision_paper_overlay_active.py"),
            "--loop",
            "--interval-sec",
            paper_interval,
            "--max-hold-hours",
            paper_max_hold,
        ]
        if paper_active_no_refresh:
            cmd.append("--no-refresh")
        specs.append(
            ProcSpec(
                name="meme_decision_paper_overlay_active",
                cmd=cmd,
                log_path=LOGS / "meme_decision_paper_overlay_active.loop.log",
            )
        )

    return specs

def _auto_apply_tuning(env: dict[str, str], procs: dict[str, subprocess.Popen]) -> None:
    """Optionally apply next_tuning.json and restart meme_bot.

    Controlled by EDGE_DECIDER_AUTO_APPLY=1 (default off).
    """
    enabled = str(env.get("EDGE_DECIDER_AUTO_APPLY", "")).strip().lower() in ("1", "true", "yes")
    if not enabled:
        return
    if not NEXT_TUNING.exists():
        return
    try:
        obj = json.loads(NEXT_TUNING.read_text(encoding="utf-8"))
    except Exception:
        return
    if not isinstance(obj, dict):
        return
    gen = float(obj.get("generated_at") or 0.0)
    change = obj.get("change") if isinstance(obj.get("change"), dict) else {}
    if not gen or not change:
        return

    # Keep a tiny in-memory guard in procs dict to avoid re-applying the same proposal.
    last_gen = getattr(_auto_apply_tuning, "_last_gen", 0.0)  # type: ignore[attr-defined]
    if gen <= float(last_gen or 0.0):
        return
    setattr(_auto_apply_tuning, "_last_gen", gen)  # type: ignore[attr-defined]

    try:
        with open(AUTO_TUNING_LOG, "a", encoding="utf-8") as fh:
            fh.write(f"{time.time():.0f} apply_next_tuning gen={gen} change_keys={list(change.keys())}\n")
    except Exception:
        pass

    # Apply env updates to .env.
    try:
        subprocess.run(
            [PYTHON, "-u", str(BASE / "scripts" / "apply_next_tuning.py")],
            cwd=str(BASE),
            env=env,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=10,
            check=False,
        )
    except Exception:
        return

    # Restart meme_bot so new env is loaded (build_env reloads .env).
    try:
        proc = procs.get("meme_bot")
        if proc and proc.poll() is None:
            proc.terminate()
    except Exception:
        pass


def _maybe_reap_stale_positions(env: dict[str, str]) -> None:
    """Best-effort hygiene: mark extremely old DB 'open' positions as stale.

    This prevents dashboards/tools from treating week-old crash leftovers as active.
    """
    # Run at most once per hour.
    last = getattr(_maybe_reap_stale_positions, "_last_run", 0.0)  # type: ignore[attr-defined]
    if last and (time.time() - float(last)) < 3600:
        return
    setattr(_maybe_reap_stale_positions, "_last_run", time.time())  # type: ignore[attr-defined]

    hours_raw = str(env.get("MEME_REAP_STALE_OPEN_HOURS") or "").strip()
    # If not configured, still do a conservative reap (24h) because it is safe and
    # helps prevent confusion when iterating quickly.
    if not hours_raw:
        hours_raw = "24"
    try:
        hours = float(hours_raw)
    except Exception:
        return
    if hours <= 0:
        return
    try:
        res = subprocess.run(
            [PYTHON, "-u", str(BASE / "scripts" / "reap_stale_positions.py")],
            cwd=str(BASE),
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=12,
            check=False,
            text=True,
        )
        out = (res.stdout or "").strip()
        if out:
            with open(REAP_LOG, "a", encoding="utf-8") as fh:
                fh.write(f"{time.time():.0f} {out}\n")
    except Exception:
        return


def main() -> int:
    # Detach from any controlling terminal/process group so this supervisor survives
    # when launched from a short-lived wrapper (e.g. editor tool invocation).
    try:
        os.setsid()
    except Exception:
        pass

    if not _acquire_singleton_lock():
        try:
            with open(LOGS / "meme_pipeline_supervisor.log", "a", encoding="utf-8") as slog:
                slog.write(f"{time.time():.0f} supervisor_exit duplicate_instance\n")
        except Exception:
            pass
        print("meme_pipeline_supervisor: another instance is already running; exiting.")
        return 0

    # Load once at startup for initial settings.
    load_dotenv(dotenv_path=str(BASE / ".env"), override=True)

    supervisor_log = LOGS / "meme_pipeline_supervisor.log"
    env = build_env()

    # Append an auto session log entry so we keep state across long runs.
    try:
        subprocess.run(
            [PYTHON, "-u", str(BASE / "scripts" / "codex_session_log.py")],
            cwd=str(BASE),
            env=env,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=8,
            check=False,
        )
    except Exception:
        pass

    procs: dict[str, subprocess.Popen] = {}

    with open(supervisor_log, "a", encoding="utf-8") as slog:
        slog.write("Supervisor start\n")
        slog.flush()

    while True:
        env = build_env()
        specs = build_specs(env)
        desired_names = {s.name for s in specs}

        # Optional: apply next tuning proposal and restart meme_bot.
        try:
            _maybe_reap_stale_positions(env)
            _auto_apply_tuning(env, procs)
        except Exception:
            pass

        # Stop any processes that are no longer desired (env changed).
        for name, proc in list(procs.items()):
            if name in desired_names:
                continue
            try:
                if proc and proc.poll() is None:
                    proc.terminate()
            except Exception:
                pass
            procs.pop(name, None)

        # spawn missing or dead processes
        for spec in specs:
            proc = procs.get(spec.name)
            if proc is None or proc.poll() is not None:
                with open(supervisor_log, "a", encoding="utf-8") as slog:
                    status = "spawn" if proc is None else f"restart(exit={proc.returncode})"
                    slog.write(f"{time.time():.0f} {spec.name} {status}\n")
                    slog.flush()
                proc = spawn(spec, env=env)
                procs[spec.name] = proc

        time.sleep(5)


if __name__ == "__main__":
    raise SystemExit(main())
